
#pragma once

#define ENGINE_APP_WIDTH 640
#define ENGINE_APP_HEIGHT 480
#define ENGINE_APP_NAME "BaseApp"

#define ENGINE_GL_CONTEXT_VERSION_MAJOR 3
#define ENGINE_GL_CONTEXT_VERSION_MINOR 3
#define ENGINE_WINDOW_RESIZABLE 0


#define ENGINE_ENABLE_LOGS 1
#define ENGINE_ENABLE_ERRORS 1